In [118]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [87]:
sns.set(style="darkgrid")
iris = sns.load_dataset("iris")

In [88]:
iris[0:4]

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa

In [89]:
iris.shape

(150, 5)

In [90]:
list(iris.columns.values)

['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

In [91]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepal_length    150 non-null float64
sepal_width     150 non-null float64
petal_length    150 non-null float64
petal_width     150 non-null float64
species         150 non-null object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB


In [92]:
iris.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

I think the data doesnt need to be rescaled

# 2

In [93]:
path = './'
df = pd.read_excel(path + "Stats_Project.xlsx")

In [94]:
df_excel_sample = df.head(100)

In [95]:
df_excel_sample.head()

customer_id  gender  is_senior_citizen partner dependents  tenure  \
0  5709-LVOEQ  Female                  0     Yes        Yes       0   
1  4075-WKNIU  Female                  0     Yes        Yes       0   
2  2775-SEFEE    Male                  0      No        Yes       8   
3  1371-DWPAZ  Female                  0     Yes        Yes      10   
4  4472-LVYGI  Female                  0     Yes        Yes      12   

   phone_service  internet_service  contract_type               payment_type  \
0              2                 1              2  Bank transfer (automatic)   
1              0                 1              2  Bank transfer (automatic)   
2              1                 0              2  Bank transfer (automatic)   
3              2                 0              2  Bank transfer (automatic)   
4              2                 0              2  Bank transfer (automatic)   

                        ...                        Unnamed: 15  Unnamed: 16  \
0                       ...                                NaN          NaN   
1                       ...                                NaN          NaN   
2                       ...                                NaN          NaN   
3                       ...                                NaN          NaN   
4                       ...                                NaN          NaN   

  Unnamed: 17       Unnamed: 18          Unnamed: 19 Unnamed: 20  \
0         NaN               NaN                  NaN         NaN   
1     Counter               NaN                  NaN         NaN   
2         NaN  Total_Group_Size  Percentage_of_total       Churn   
3      Female              3488             0.495244         921   
4        Male              3555             0.504756         948   

                 Unnamed: 21                Unnamed: 22 Unnamed: 23  \
0                        NaN                        NaN         NaN   
1  Percentage_of_Churn_Group  Percentage_of_Churn_Total         NaN   
2                        NaN                        NaN         NaN   
3                   0.264048                   0.492777         NaN   
4                   0.266667                   0.507223         NaN   

                                      Unnamed: 24  
0                                             NaN  
1                                             NaN  
2                                             NaN  
3                                             NaN  
4  probability analysis for categorical variables  

[5 rows x 25 columns]

In [96]:
df.shape

(7043, 25)

In [97]:
list(df.columns.values[:6])

['customer_id',
 'gender',
 'is_senior_citizen',
 'partner',
 'dependents',
 'tenure']

In [182]:
df.select_dtypes(include=['object']).columns

Index(['customer_id', 'gender', 'partner', 'dependents', 'payment_type',
       'churn', 'Unnamed: 15', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 24'],
      dtype='object')

In [99]:
col_names = list(df.select_dtypes('int').columns)

In [100]:
int_df = df[col_names]
int_df.describe()

is_senior_citizen       tenure  phone_service  internet_service  \
count        7043.000000  7043.000000    7043.000000       7043.000000   
mean            0.162147    32.371149       1.325004          1.222916   
std             0.368612    24.559481       0.642730          0.778877   
min             0.000000     0.000000       0.000000          0.000000   
25%             0.000000     9.000000       1.000000          1.000000   
50%             0.000000    29.000000       1.000000          1.000000   
75%             0.000000    55.000000       2.000000          2.000000   
max             1.000000    72.000000       2.000000          2.000000   

       contract_type  
count    7043.000000  
mean        0.690473  
std         0.833755  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         1.000000  
max         2.000000

In [184]:
int_df.describe().loc['max']-int_df.describe().loc['min']

is_senior_citizen     1.0
tenure               72.0
phone_service         2.0
internet_service      2.0
contract_type         2.0
dtype: float64

# 3

In [102]:
path = './'
train = pd.read_csv(path + "train.csv")

In [103]:
train.head(3)

rowid                 date  Temperature  Humidity  Light     CO2  \
0      1  2015-02-04 17:51:00        23.18   27.2720  426.0  721.25   
1      2  2015-02-04 17:51:59        23.15   27.2675  429.5  714.00   
2      3  2015-02-04 17:53:00        23.15   27.2450  426.0  713.50   

   HumidityRatio  Occupancy  
0       0.004793          1  
1       0.004783          1  
2       0.004779          1

In [104]:
train.shape

(8143, 8)

In [105]:
list(train.columns.values)

['rowid',
 'date',
 'Temperature',
 'Humidity',
 'Light',
 'CO2',
 'HumidityRatio',
 'Occupancy']

In [107]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8143 entries, 0 to 8142
Data columns (total 8 columns):
rowid            8143 non-null int64
date             8143 non-null object
Temperature      8143 non-null float64
Humidity         8143 non-null float64
Light            8143 non-null float64
CO2              8143 non-null float64
HumidityRatio    8143 non-null float64
Occupancy        8143 non-null int64
dtypes: float64(5), int64(2), object(1)
memory usage: 509.0+ KB


In [108]:
train.describe()

rowid  Temperature     Humidity        Light          CO2  \
count  8143.000000  8143.000000  8143.000000  8143.000000  8143.000000   
mean   4072.000000    20.619084    25.731507   119.519375   606.546243   
std    2350.825954     1.016916     5.531211   194.755805   314.320877   
min       1.000000    19.000000    16.745000     0.000000   412.750000   
25%    2036.500000    19.700000    20.200000     0.000000   439.000000   
50%    4072.000000    20.390000    26.222500     0.000000   453.500000   
75%    6107.500000    21.390000    30.533333   256.375000   638.833333   
max    8143.000000    23.180000    39.117500  1546.333333  2028.500000   

       HumidityRatio    Occupancy  
count    8143.000000  8143.000000  
mean        0.003863     0.212330  
std         0.000852     0.408982  
min         0.002674     0.000000  
25%         0.003078     0.000000  
50%         0.003801     0.000000  
75%         0.004352     0.000000  
max         0.006476     1.000000

In [110]:
train.rowid.unique()

array([   1,    2,    3, ..., 8141, 8142, 8143])

# 4

In [111]:
path = './'
titanic = pd.read_csv(path + "df_csv.csv")

In [120]:
titanic.iloc[np.r_[0:5, -5:0]]

passenger_id  survived  pclass     sex   age  sibsp  parch     fare  \
0               0         0       3    male  22.0      1      0   7.2500   
1               1         1       1  female  38.0      1      0  71.2833   
2               2         1       3  female  26.0      0      0   7.9250   
3               3         1       1  female  35.0      1      0  53.1000   
4               4         0       3    male  35.0      0      0   8.0500   
886           886         0       2    male  27.0      0      0  13.0000   
887           887         1       1  female  19.0      0      0  30.0000   
888           888         0       3  female   NaN      1      2  23.4500   
889           889         1       1    male  26.0      0      0  30.0000   
890           890         0       3    male  32.0      0      0   7.7500   

    embarked   class deck  embark_town  alone  
0          S   Third  NaN  Southampton      0  
1          C   First    C    Cherbourg      0  
2          S   Third  NaN  Southampton      1  
3          S   First    C  Southampton      0  
4          S   Third  NaN  Southampton      1  
886        S  Second  NaN  Southampton      1  
887        S   First    B  Southampton      1  
888        S   Third  NaN  Southampton      0  
889        C   First    C    Cherbourg      1  
890        Q   Third  NaN   Queenstown      1

In [121]:
titanic.shape

(891, 13)

In [125]:
list(titanic.columns.values)

['passenger_id',
 'survived',
 'pclass',
 'sex',
 'age',
 'sibsp',
 'parch',
 'fare',
 'embarked',
 'class',
 'deck',
 'embark_town',
 'alone']

In [126]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
passenger_id    891 non-null int64
survived        891 non-null int64
pclass          891 non-null int64
sex             891 non-null object
age             714 non-null float64
sibsp           891 non-null int64
parch           891 non-null int64
fare            891 non-null float64
embarked        889 non-null object
class           891 non-null object
deck            203 non-null object
embark_town     889 non-null object
alone           891 non-null int64
dtypes: float64(2), int64(6), object(5)
memory usage: 90.6+ KB


In [127]:
titanic.describe()

passenger_id    survived      pclass         age       sibsp  \
count    891.000000  891.000000  891.000000  714.000000  891.000000   
mean     445.000000    0.383838    2.308642   29.699118    0.523008   
std      257.353842    0.486592    0.836071   14.526497    1.102743   
min        0.000000    0.000000    1.000000    0.420000    0.000000   
25%      222.500000    0.000000    2.000000   20.125000    0.000000   
50%      445.000000    0.000000    3.000000   28.000000    0.000000   
75%      667.500000    1.000000    3.000000   38.000000    1.000000   
max      890.000000    1.000000    3.000000   80.000000    8.000000   

            parch        fare       alone  
count  891.000000  891.000000  891.000000  
mean     0.381594   32.204208    0.602694  
std      0.806057   49.693429    0.489615  
min      0.000000    0.000000    0.000000  
25%      0.000000    7.910400    0.000000  
50%      0.000000   14.454200    1.000000  
75%      0.000000   31.000000    1.000000  
max      6.000000  512.329200    1.000000

# print the unique values for each categorical variables. If there are more than 5 distince values, print the top 5 in terms of prevelence or frequency.

In [136]:
titanic.nunique()

passenger_id    891
survived          2
pclass            3
sex               2
age              88
sibsp             7
parch             7
fare            248
embarked          3
class             3
deck              7
embark_town       3
alone             2
dtype: int64

In [188]:
# colname = list(titanic.columns.values)

# for val in titanic[colname].unique():
#     print(val)
    
    
# for val in titanic['deck'].unique():
#     print(val)
    
n = []
i = []
for t in titanic.columns[:]:
    n.append(titanic[t].unique())
    i.append(t)

unique = pd.DataFrame( n, index=i).T
unique.head()

passenger_id survived pclass     sex  age sibsp parch     fare embarked  \
0            0        0      3    male   22     1     0     7.25        S   
1            1        1      1  female   38     0     1  71.2833        C   
2            2     None      2    None   26     3     2    7.925        Q   
3            3     None   None    None   35     4     5     53.1      NaN   
4            4     None   None    None  NaN     2     3     8.05     None   

    class deck  embark_town alone  
0   Third  NaN  Southampton     0  
1   First    C    Cherbourg     1  
2  Second    E   Queenstown  None  
3    None    G          NaN  None  
4    None    D         None  None

In [176]:
colnames = list(titanic.columns.values)

In [190]:
for colnames in titanic:
    print(titanic[colnames].head().unique())

[0 1 2 3 4]
[0 1]
[3 1]
['male' 'female']
[22. 38. 26. 35.]
[1 0]
[0]
[ 7.25   71.2833  7.925  53.1     8.05  ]
['S' 'C']
['Third' 'First']
[nan 'C']
['Southampton' 'Cherbourg']
[0 1]


In [186]:
cols = ["survived", "pclass", "sibsp", "parch", "embarked", "class", "deck", "alone"]
for col in cols:
    print(f"{col}: {pd.Series(titanic[col].value_counts().index.values).unique()[:5]}")

survived: [0 1]
pclass: [3 1 2]
sibsp: [0 1 2 4 3]
parch: [0 1 2 5 3]
embarked: ['S' 'C' 'Q']
class: ['Third' 'First' 'Second']
deck: ['C' 'B' 'D' 'E' 'A']
alone: [1 0]


In [189]:
tit_obj = titanic.select_dtypes(object)
for col in tit_obj:
    print(col, (titanic[col].unique()[:5]))

sex ['male' 'female']
embarked ['S' 'C' 'Q' nan]
class ['Third' 'First' 'Second']
deck [nan 'C' 'E' 'G' 'D']
embark_town ['Southampton' 'Cherbourg' 'Queenstown' nan]


In [192]:
{col: list(titanic[col].unique())[:5] for col in titanic.select_dtypes(object)}

{'sex': ['male', 'female'],
 'embarked': ['S', 'C', 'Q', nan],
 'class': ['Third', 'First', 'Second'],
 'deck': [nan, 'C', 'E', 'G', 'D'],
 'embark_town': ['Southampton', 'Cherbourg', 'Queenstown', nan]}